pipeline {

    agent any


    tools {
        sonarRunner 'sonar-scanner'
    }


    environment {

        SONAR_PROJECT_KEY = "Electronic-shop"

        DOCKER_SERVER = "ec2-user@54.89.204.152"

        DOCKER_IMAGE = "electronic-shop"

        DOCKER_CONTAINER = "electronic-shop-container"

    }


    stages {


        stage('Checkout Code') {

            steps {

                echo "Cloning GitHub repository"

                git branch: 'main',
                    url: 'https://github.com/hs-44/Electronics-Shop.git'

            }
        }



        stage('SonarQube Analysis') {

            steps {

                echo "Starting SonarQube Scan"


                withSonarQubeEnv('sonar-server') {


                    sh """

                    sonar-scanner \
                    -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                    -Dsonar.sources=.

                    """

                }

            }

        }



        stage('Docker Build') {

            steps {

                echo "Building Docker Image"


                sh """

                docker build \
                -t ${DOCKER_IMAGE}:latest .

                """

            }

        }



        stage('Copy Image To Docker Server') {

            steps {

                echo "Copying Docker image"


                sh """

                docker save \
                ${DOCKER_IMAGE}:latest \
                -o ${DOCKER_IMAGE}.tar


                scp ${DOCKER_IMAGE}.tar \
                ${DOCKER_SERVER}:/tmp/${DOCKER_IMAGE}.tar


                """

            }

        }



        stage('Deploy On Docker Server') {

            steps {

                echo "Deploying application"


                sh """

                ssh ${DOCKER_SERVER} << EOF


                docker load \
                -i /tmp/${DOCKER_IMAGE}.tar


                docker stop ${DOCKER_CONTAINER} || true


                docker rm ${DOCKER_CONTAINER} || true


                docker run -d \
                --name ${DOCKER_CONTAINER} \
                -p 80:80 \
                ${DOCKER_IMAGE}:latest


EOF

                """

            }

        }


    }



    post {


        success {

            echo "===================================="
            echo "BUILD SUCCESS"
            echo "Application URL:"
            echo "http://54.89.204.152"
            echo "===================================="

        }


        failure {

            echo "BUILD FAILED - Check Console Output"

        }

    }

}
