pipeline {

    agent any

    environment {

        SONAR_PROJECT_KEY = "Electronic-shop"

        DOCKER_SERVER = "ubuntu@54.89.204.152"

        REMOTE_PATH = "/home/ubuntu/website1"

        DOCKER_IMAGE = "electronic-shop"

        DOCKER_CONTAINER = "electronic-shop-container"

    }


    stages {


        stage('Checkout Code') {

            steps {

                echo "Getting code from GitHub"

                git branch: 'main',
                    url: 'https://github.com/hs-44/Electronics-Shop.git'

            }

        }



        stage('SonarQube Analysis') {

            steps {

                echo "SonarQube Scan"

                withSonarQubeEnv('sonar-server') {

                    script {

                        def scannerHome = tool 'sonar-scanner'

                        sh """

                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                        -Dsonar.sources=.

                        """

                    }

                }

            }

        }



        stage('Copy Code To Docker Server') {

            steps {

                echo "Copying code to Docker server"


                sh """

                ssh ${DOCKER_SERVER} '

                rm -rf ${REMOTE_PATH}/*

                '


                scp -r * ${DOCKER_SERVER}:${REMOTE_PATH}/


                """

            }

        }



        stage('Docker Build') {

            steps {

                echo "Building Docker Image on Docker Server"


                sh """

                ssh ${DOCKER_SERVER} '

                cd ${REMOTE_PATH}


                docker build \
                -t ${DOCKER_IMAGE}:latest .


                '

                """

            }

        }



        stage('Deploy Container') {

            steps {

                echo "Running Container"


                sh """

                ssh ${DOCKER_SERVER} '

                docker stop ${DOCKER_CONTAINER} || true


                docker rm ${DOCKER_CONTAINER} || true


                docker run -d \
                --name ${DOCKER_CONTAINER} \
                -p 80:80 \
                ${DOCKER_IMAGE}:latest


                '

                """

            }

        }


    }


    post {

        success {

            echo "Deployment completed successfully"

        }


        failure {

            echo "Deployment failed"

        }

    }

}
