pipeline {

    agent any

    environment {
        SONAR_PROJECT_KEY = "Electronic-shop"
        DOCKER_SERVER = "ubuntu@54.89.204.152"
        DOCKER_PATH = "/home/ubuntu/website1/Metronic-Shop-UI-master/Metronic-Shop-UI-master"
        IMAGE_NAME = "electronic-shop"
    }


    stages {

        stage('Checkout Code') {
            steps {
                echo "Getting code from GitHub"

                git branch: 'main',
                    url: 'https://github.com/hs-44/Electronics-Shop.git'
            }
        }


        stage('SonarQube Analysis') {

            steps {

                echo "SonarQube Scan"

                withSonarQubeEnv('sonar-server') {

                    script {

                        def scannerHome = tool 'sonar-scanner'

                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                        -Dsonar.sources=.
                        """

                    }
                }
            }
        }



        stage('Copy Code To Docker Server') {

            steps {

                echo "Copying code to Docker server"

                sshagent(['ubuntu_docker']) {

                    sh """

                    ssh -o StrictHostKeyChecking=no ${DOCKER_SERVER} '
                    
                    rm -rf ${DOCKER_PATH}/*
                    mkdir -p ${DOCKER_PATH}

                    '

                    scp -o StrictHostKeyChecking=no -r ./* ${DOCKER_SERVER}:${DOCKER_PATH}/

                    """
                }

            }
        }



        stage('Docker Build') {

            steps {

                echo "Building Docker Image on Docker Server"

                sshagent(['ubuntu_docker']) {

                    sh """

                    ssh -o StrictHostKeyChecking=no ${DOCKER_SERVER} '

                    cd ${DOCKER_PATH}

                    docker build -t ${IMAGE_NAME}:latest .

                    '

                    """

                }

            }

        }



        stage('Deploy Container') {

            steps {

                echo "Deploying Container"

                sshagent(['ubuntu_docker']) {

                    sh """

                    ssh -o StrictHostKeyChecking=no ${DOCKER_SERVER} '

                    docker stop electronic-container || true

                    docker rm electronic-container || true


                    docker run -d \
                    --name electronic-container \
                    -p 80:80 \
                    ${IMAGE_NAME}:latest

                    '

                    """

                }

            }

        }

    }



    post {

        success {

            echo "Deployment Successful"

        }

        failure {

            echo "Deployment Failed"

        }

    }

}
